workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: EC-Remote Key   # نفس الاسم الموجود بالصورة

    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APP_ID: 6751927803  # ID تطبيقك من App Store Connect

    scripts:
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release 

    publishing:
      app_store_connect:
        auth: integration   # يعني رح يستخدم المفتاح المضاف
        submit_to_testflight: true
        submit_to_app_store: false



