workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID


