workflows:
  ios-appstore-manual:
    name: iOS App Store (manual signing)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect   # ✅ رح يقرأ المتغيرات APP_STORE_API_KEY و APP_STORE_ISSUER_ID و APP_STORE_KEY_ID من هون

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Show versions
        script: |
          set -e
          flutter --version
          xcodebuild -version
          pod --version

      - name: Ensure valid iOS Podfile
        script: |
          set -e
          cat > ios/Podfile <<'EOF'
          platform :ios, '13.0'

          use_frameworks!
          use_modular_headers!

          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), File.expand_path('..', _dir_))

          flutter_ios_podfile_setup

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(_FILE_))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      - name: Flutter prep
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: iOS Pods (install)
        script: |
          set -e
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Set up manual code signing
        script: |
          set -e
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (release)
        script: |
          set -e
          xcode-project build-ipa \
            --workspace=ios/Runner.xcworkspace \
            --scheme=Runner \
            --archive-flags="-allowProvisioningUpdates"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true