workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
          distribution_type: app_store
          bundle_identifier: com.drd.ecremote

      groups:
        - app_store_connect

    scripts:
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          # تأكد من use_frameworks! :linkage => :static
          if ! grep -q "use_frameworks!" Podfile; then
            sed -i '' "1s;^;use_frameworks! :linkage => :static\n;" Podfile
          fi
          # post_install لإيقاف توقيع الـ Pods
          if ! grep -q "CODE_SIGNING_ALLOWED" Podfile; then
            cat >> Podfile <<'RUBY'
          post_install do |installer|
            installer.pods_project.targets.each do |t|
              t.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              end
            end
          end
          RUBY
          fi
          pod repo update
          pod install
          cd ..

      - name: Set up code signing on Xcode project (use profiles)
        script: xcode-project use-profiles

      - name: Create ExportOptions.plist (App Store)
        script: |
          cat > ios/ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.drd.ecremote</key><string>EC-Remote Distribution</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      - name: Build IPA (App Store export)
        script: |
          flutter build ipa --release --no-tree-shake-icons \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
