workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # يخلي Codemagic يجلب ملفات التوقيع المناسبة أوتوماتيكياً
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

      vars:
        BUNDLE_ID: com.drd.ecremote

      # لو خزنـتِ مفاتيح App Store Connect كمتغيرات في User/Team settings
      # ضيفي اسم المجموعة اللي فيها المتغيرات
      groups:
        - app_store_connect   # APP_STORE_API_KEY, APP_STORE_KEY_ID, APP_STORE_ISSUER_ID

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          # ثبّت platform إلى iOS 13 (يعدّل إن وجد وإلا يضيفه)
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Bump iOS build number (auto)
        script: |
          # رقم بناء أوتوماتيكي (وقت يونكس) حتى يكون فريد
          export BUILD_NUMBER=$(date +%s)
          echo "Using BUILD_NUMBER=$BUILD_NUMBER"

          # حدّث CFBundleVersion في Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          # مرّر رقم البناء نفسه إلى Flutter (اختياري لكنه مفيد لو حابة تزامنيه)
          flutter build ipa --release --no-tree-shake-icons --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        # المفاتيح من المتغيرات (المجموعة app_store_connect)
        api_key: $APP_STORE_API_KEY        # محتوى ملف .p8 بشكل Base64
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        # ممكن تحددي مجموعة بيتا معيّنة إن وجدت