workflows:
  ios-testflight:
    name: iOS TestFlight (auto-sign + debug)
    max_build_duration: 60

    # هذا الاسم هو مفاتيح App Store Connect للنشر (ليس سحب البروفايل)
    integrations:
      app_store_connect: CodemagicKey

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # تفعيل التوقيع التلقائي عبر Codemagic (يجلب شهادة وبروفايل)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get

      - name: Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      # ====== DEBUG قبل البناء ======
      - name: Debug signing (before build)
        script: |
          echo "=== whoami & Xcode ==="
          whoami || true
          xcodebuild -version || true

          echo "=== App record (bundle id) from Info.plist ==="
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/Runner/Info.plist || true

          echo "=== Keychain identities (code signing) ==="
          security find-identity -v -p codesigning || true

          echo "=== Provisioning Profiles folder ==="
          ls -al ~/Library/MobileDevice/Provisioning\ Profiles || echo "No profiles directory"

          echo "=== Show Xcode build settings (Release) ==="
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner -configuration Release -showBuildSettings \
            | egrep "CODE_SIGN|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING_PROFILE" || true

      - name: Build IPA (auto-sign)
        script: |
          # Flutter سيستخدم xcodebuild مع التوقيع التلقائي المفعّل بواسطة ios_signing
          flutter build ipa --release --no-tree-shake-icons

      # ====== DEBUG بعد البناء (إذا فشل الأرشفة غالباً ما زال مفيد) ======
      - name: Debug signing (after build)
        script: |
          echo "=== Archive path check ==="
          ls -al build/ios/archive || true
          echo "=== IPA path check ==="
          ls -al build/ios/ipa || true
          echo "=== Profiles after build ==="
          ls -al ~/Library/MobileDevice/Provisioning\ Profiles || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        submit_to_testflight: true