workflows:
  # ========= ANDROID =========
  android-debug:
    name: Android Debug (APK)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  android-release-apk:
    name: Android Release (APK)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  android-release-aab:
    name: Android Release (AAB for Play)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab


  ios-testflight:
    name: iOS TestFlight (manual signing)
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        # ⚠️ لا تضيفي distribution_type هنا مع المراجع اليدوية
        certificates:
          - EC-Remote Distribution     # مثال: Apple Distribution (Codemagic)
        provisioning_profiles:
          - EC-Remote Distribution   # مثال: AppStore com.drd.ecremote
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true