workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote
      groups:
        - app_store_connect   # فيها APP_STORE_API_KEY / APP_STORE_KEY_ID / APP_STORE_ISSUER_ID

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA (uses auto version + build number)
        script: |
          BN=${BUILD_NUMBER:-${CM_BUILD_ID:-1}}
          flutter build ipa --release --no-tree-shake-icons \
            --build-name=1.0.$BN --build-number=$BN
          echo "IPA files:"; ls -lah build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true