workflows:
  ios-appstore:
    name: iOS App Store / TestFlight (IPA)

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store     # <-- يطلب Distribution (App Store)
        bundle_identifier: com.drd.ecremote   # <-- يطابق الـ App ID
    scripts:
      - flutter pub get
      - xcode-project use-profiles
      - flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true