workflows:
  ios-appstore:
    name: iOS App Store (Automatic signing)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      # 1) Show versions
      - name: Show versions
        script: |
          flutter --version
          xcodebuild -version
          pod --version

      # 2) Flutter clean & get
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get

      # 3) Install iOS Pods
      - name: iOS Pods (install)
        script: |
          cd ios
          pod install
          cd ..

      # 4) Build IPA (App Store)
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace=ios/Runner.xcworkspace \
            --scheme=Runner \
            --archive-flags="-allowProvisioningUpdates"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID


