workflows:
  # ========= ANDROID =========
  android-debug:
    name: Android Debug (APK)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  android-release-apk:
    name: Android Release (APK)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      # لو عندك keystore مضاف في Codemagic استخدم التوقيع التلقائي:
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  android-release-aab:
    name: Android Release (AAB for Play)
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

  # ========= iOS =========
  ios-simulator:
    name: iOS Simulator (.app, بدون توقيع)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app

  ios-adhoc:
    name: iOS AdHoc (IPA للأجهزة المسجّلة)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --export-options-plist=ExportOptions_AdHoc.plist
    artifacts:
      - build/ios/ipa/*.ipa

  ios-appstore:
    name: iOS App Store / TestFlight (IPA)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --export-options-plist=ExportOptions_AppStore.plist
    artifacts:
      - build/ios/ipa/*.ipa