workflows:
  ios-appstore-manual:
    name: iOS App Store (manual signing + TestFlight)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_KEY_ID: Encrypted(...) # بتحطي قيمتك من CodeMagic
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # بتحطي قيمتك من CodeMagic
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # بتحطي قيمتك من CodeMagic

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      # 0) معلومات للتشخيص
      - name: Show versions
        script: |
          set -e
          flutter --version
          xcodebuild -version
          pod --version

      # 1) إصلاح Podfile إذا فيه dir
      - name: Fix Podfile dir reference
        script: |
          set -e
          if grep -q "dir" ios/Podfile; then
            echo "⚠️ Fixing dir -> _dir_ in Podfile"
            sed -i.bak "s/dir/_dir_/g" ios/Podfile
          fi

      # 2) تنظيف Pods والكاش
      - name: Clean iOS Pods
        script: |
          set -e
          rm -rf ios/Podfile.lock
          rm -rf ios/Pods
          rm -rf ~/Library/Caches/CocoaPods
          pod repo update

      # 3) Flutter prep
      - name: Flutter prep
        script: |
          set -e
          flutter clean
          flutter pub get

      # 4) Pods
      - name: iOS Pods (install)
        script: |
          set -e
          cd ios
          pod install
          cd ..

      # 5) تفعيل الشهادات والبروفايلات المرفوعة في Code signing
      - name: Set up manual code signing
        script: |
          set -e
          keychain add-certificates
          xcode-project use-profiles

      # 6) بناء IPA (App Store)
      - name: Build IPA (release)
        script: |
          set -e
          xcode-project build-ipa \
            --workspace=ios/Runner.xcworkspace \
            --scheme=Runner \
            --archive-flags="-allowProvisioningUpdates"

      # 7) رفع تلقائي على TestFlight
      - name: Publish to TestFlight
        script: |
          set -e
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          app-store-connect publish \
            --path "$IPA_PATH" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive