workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote
      groups:
        - app_store_connect

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Show versions
        script: |
          set -e
          flutter --version
          ruby --version
          pod --version
          xcodebuild -version

      # (اختياري) إصلاح Podfile مرة واحدة
      - name: Ensure valid iOS Podfile
        script: |
          cat > ios/Podfile <<'EOF'
          platform :ios, '13.0'
          use_frameworks!
          use_modular_headers!
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }
          require File.expand_path(File.join('packages','flutter_tools','bin','podhelper'), File.expand_path('..', __dir__))
          flutter_ios_podfile_setup
          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(_FILE_))
          end
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      - name: Flutter prep
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: iOS Pods (install)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      # لا تبني iOS هنا؛ بس احسبي رقم البناء وصدّريه كمتغيّر
      - name: Compute build number
        script: |
          set -e
          CURRENT=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" ios/Runner/Info.plist 2>/dev/null || echo 0)
          NEW_BUILD_NUMBER=$((CURRENT + 1))
          echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" | tee -a $CM_ENV
          echo "Will use build number: $NEW_BUILD_NUMBER"

      # خلي كودماجيك يحقن البروفايلات قبل البناء
      - name: Set up code signing on Xcode project (auto)
        script: |
          set -e
          xcode-project use-profiles

      - name: Build IPA (release)
        script: |
          set -e
          flutter build ipa --release --no-tree-shake-icons --build-number="$NEW_BUILD_NUMBER"

      - name: Debug archive contents (post)
        script: |
          set -e
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          echo "IPA_PATH=$IPA_PATH"
          TMP=$(mktemp -d)
          unzip -q "$IPA_PATH" -d "$TMP"
          APP="$TMP/Payload/Runner.app"
          echo "Bundle ID:"
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$APP/Info.plist" || true
          test -f "$APP/embedded.mobileprovision" && echo "embedded.mobileprovision FOUND" || echo "embedded.mobileprovision MISSING"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY      # محتوى ملف .p8 بصيغة Base64
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true