workflows:
  ios-appstore-manual:
    name: iOS App Store (manual signing + TestFlight)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect   # APP_STORE_API_KEY / APP_STORE_KEY_ID / APP_STORE_ISSUER_ID

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Show versions & commit
        script: |
          set -e
          flutter --version
          xcodebuild -version
          pod --version
          echo "HEAD commit:"
          git show -s --oneline HEAD
          echo "Current branch:"
          git rev-parse --abbrev-ref HEAD

      - name: Print Podfile as received
        script: |
          set -e
          echo "===== ios/Podfile (BEFORE) ====="
          test -f ios/Podfile && sed -n '1,160p' ios/Podfile || echo "Podfile missing"

      # يصلّح dir لو موجود
      - name: Quick fix _dir_ -> __dir__
        script: |
          set -e
          if test -f ios/Podfile && grep -q "dir" ios/Podfile; then
            echo "⚠️ Found dir in Podfile. Fixing to _dir_..."
            sed -i.bak "s/dir/_dir_/g" ios/Podfile
          fi

      # لو لسه في مشاكل، نعيد كتابة Podfile بنسخة Flutter سليمة 100%
      - name: Force a clean Flutter Podfile
        script: |
          set -e
          cat > ios/Podfile <<'EOF'
          platform :ios, '13.0'
          use_frameworks!
          use_modular_headers!
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          project 'Runner', { 'Debug' => :debug, 'Profile' => :release, 'Release' => :release }

          # Flutter podhelper (صيغة سليمة بدون dir):
          require File.expand_path(File.join('..', 'Flutter', 'podhelper'), __dir__)

          flutter_ios_podfile_setup

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      - name: Show Podfile after fix
        script: |
          set -e
          echo "===== ios/Podfile (AFTER) ====="
          sed -n '1,160p' ios/Podfile

      - name: Clean iOS Pods & repos
        script: |
          set -e
          rm -rf ios/Podfile.lock ios/Pods ~/Library/Caches/CocoaPods
          pod repo update

      - name: Flutter prep
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: iOS Pods (install)
        script: |
          set -e
          cd ios
          pod install
          cd ..

      - name: Set up manual code signing
        script: |
          set -e
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (release)
        script: |
          set -e
          xcode-project build-ipa \
            --workspace=ios/Runner.xcworkspace \
            --scheme=Runner \
            --archive-flags="-allowProvisioningUpdates"

      - name: Publish to TestFlight
        script: |
          set -e
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          echo "Uploading: $IPA_PATH"
          app-store-connect publish \
            --path "$IPA_PATH" \
            --api-key "$APP_STORE_API_KEY" \
            --key-id "$APP_STORE_KEY_ID" \
            --issuer-id "$APP_STORE_ISSUER_ID"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

