workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # التوقيع: نستخدم بروفايل التوزيع الموجود في حسابك
      ios_signing:
        provisioning_profiles:
          - bundle_identifier: com.drd.ecremote
            profile: "EC-Remote AppStore Profile"   # الاسم تماماً كما في Apple Developer

      # مجموعة مفاتيح App Store Connect (مضافة عندك كمتغيرات سرّية)
      groups:
        - app_store_connect

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Bump version (patch) + set build number
        script: |
          # زيادة build number تلقائياً
          PLIST="ios/Runner/Info.plist"
          CURRENT=$(PlistBuddy -c "Print CFBundleVersion" "$PLIST" 2>/dev/null || echo "0")
          NEW=$(( ${CURRENT:-0} + 1 ))
          PlistBuddy -c "Set :CFBundleVersion $NEW" "$PLIST" || PlistBuddy -c "Add :CFBundleVersion string $NEW" "$PLIST"
          echo "Using build number: $NEW"

      - name: Set up code signing on Xcode project (use profiles)
        script: |
          xcode-project use-profiles

      - name: Create ExportOptions.plist (App Store)
        script: |
          cat > ios/ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.drd.ecremote</key>
              <string>EC-Remote AppStore Profile</string>
            </dict>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Build IPA (App Store export)
        script: |
          flutter build ipa --release --no-tree-shake-icons \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY       # محتوى ملف .p8 بصيغة Base64
        key_id:  $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        # beta_groups: