workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

      vars:
        BUNDLE_ID: com.drd.ecremote

      groups:
        - app_store_connect   # لازم تكوني ضايفة المتغيرات (API_KEY, KEY_ID, ISSUER_ID) من Codemagic settings

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          # تثبيت الـ platform iOS 13
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi

          # تنظيف وإعادة تثبيت الـ pods
          rm -rf Podfile.lock Pods
          pod repo update
          pod install --repo-update
          cd ..

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        # ممكن تحددي مجموعة بيتا معيّنة إن وجدت