workflows:
  ios-testflight:
    name: iOS TestFlight (manual signing + debug)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        provisioning_profiles:
          - profile: "EC-Remote AppStore Profile"

      groups:
        - app_store_connect

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Debug signing context (pre)
        script: |
          set -x
          whoami
          xcodebuild -version
          security find-identity -v -p codesigning || true
          echo "=== Installed Provisioning Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles || true

      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Force manual code signing
        script: |
          xcode-project use-profiles

      - name: Create ExportOptions.plist (App Store)
        script: |
          cat > ios/ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.drd.ecremote</key>
              <string>EC-Remote AppStore Profile</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF
          echo "Created ios/ExportOptions.plist:"
          cat ios/ExportOptions.plist

      - name: Build IPA (App Store export)
        script: |
          flutter build ipa --release --no-tree-shake-icons \
            --export-options-plist=ios/ExportOptions.plist

      - name: Debug archive contents (post)
        script: |
          echo "=== XCARCHIVE tree ==="
          ls -R build/ios/archive || true
          ARCHIVE=$(ls -d build/ios/archive/*.xcarchive | head -1)
          if [ -d "$ARCHIVE" ]; then
            echo "Archive: $ARCHIVE"
            /usr/libexec/PlistBuddy -c 'Print :ApplicationProperties:CFBundleIdentifier' "$ARCHIVE/Info.plist" || true
            echo "Embedded mobileprovision name:"
            strings "$ARCHIVE/Products/Applications/Runner.app/embedded.mobileprovision" | grep -A1 '<key>Name</key>' | head -4 || true
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true