workflows:
  ios-appstore:
    name: iOS App Store / TestFlight (IPA)
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote   # << مهم جداً
    scripts:
      - flutter clean
      - flutter pub get
      # يضبط Signing/Profiles على مشروع Xcode قبل البناء
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build Runner scheme only
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $PWD/build/Runner.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/ExportOptions.plist \-exportPath $PWD/build/ios
      # بناء IPA (Runner هو السكيم الافتراضي بتطبيقات Flutter)
      - flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true