workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # نطلب من كودماجيك استخدام بروفايل App Store لهذا الـ bundle id
      ios_signing:
        bundle_identifier: com.drd.ecremote
        provisioning_profiles:
          - profile: EC-Remote AppStore Profile   # اكتب الاسم الظاهر عندك تماماً

      vars:
        BUNDLE_ID: com.drd.ecremote

      groups:
        - app_store_connect   # فيها مفاتيح App Store Connect

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          # اضبط platform :ios, '13.0'
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Set up code signing on Xcode project (use profiles)
        script: |
          # يفعّل التوقيع اليدوي داخل المشروع ويختار بروفايل App Store المطابق
          xcode-project use-profiles

      - name: Bump version (patch) + set build number
        script: |
          # رقم النسخة من pubspec ورقم البناء من عدّاد كودماجيك
          APP_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //; s/+.*//')
          BUILD_NUMBER=$CM_BUILD_NUMBER
          echo "Using version $APP_VERSION ($BUILD_NUMBER)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist

      - name: Build IPA (App Store export)
        script: |
          # مهم: نحدد export-method=app-store حتى يستخدم شهادة التوزيع وبروفايل App Store
          flutter build ipa --release --no-tree-shake-icons --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        # بإمكانك تحديد مجموعة تجريب داخل TestFlight لو موجودة
        # beta_groups: