workflows:
  ios-testflight:
    name: iOS TestFlight (auto-sign)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        # توقيع تلقائي للتوزيع App Store حسب الـ Bundle ID
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

      vars:
        BUNDLE_ID: com.drd.ecremote

      groups:
        - app_store_connect   # (APP_STORE_API_KEY / APP_STORE_KEY_ID / APP_STORE_ISSUER_ID)

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Bump version (patch) + set build number
        script: |
          # رفّعي build number تلقائياً
          PLIST=ios/Runner/Info.plist
          CURRENT=$(PlistBuddy -c "Print CFBundleVersion" "$PLIST" 2>/dev/null || echo "0")
          NEW_BUILD=$(( ${CURRENT:-0} + 1 ))
          PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" || PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD" "$PLIST"
          echo "Using build number: $NEW_BUILD"

      - name: Build IPA (auto-sign)
        script: |
          # مهم: بدون ExportOptions.plist — خلي كودماجيك يدير التوقيع والتصدير
          flutter build ipa --release --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true