workflows:
  ios-testflight:
    name: iOS TestFlight (Codemagic)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

      vars:
        BUNDLE_ID: com.drd.ecremote

      groups:
        - app_store_connect   # APP_STORE_API_KEY / APP_STORE_KEY_ID / APP_STORE_ISSUER_ID

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Bump version (patch) + set build number
        script: |
          # اقرأ النسخة الحالية من pubspec.yaml (شكلها: version: 1.2.3+45)
          CURRENT_LINE=$(grep -E '^version:' pubspec.yaml | head -n1 | awk '{print $2}')
          CURRENT_SEMVER=${CURRENT_LINE%%+*}      # 1.2.3
          IFS='.' read -r MAJ MIN PAT <<< "$CURRENT_SEMVER"
          NEW_PATCH=$((PAT+1))
          NEW_SEMVER="${MAJ}.${MIN}.${NEW_PATCH}"  # مثال: 1.2.4

          # استخدم build number الجاهز من Codemagic
          echo "New version: ${NEW_SEMVER}  |  Build number: ${BUILD_NUMBER}"

          # نخلي Flutter يستخدمهم مباشرة بدون تعديل الملف
          echo "BUILD_NAME=${NEW_SEMVER}" >> $CM_ENV
          echo "BUILD_NUMBER_VAL=${BUILD_NUMBER}" >> $CM_ENV

      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA (uses auto version + build number)
        script: |
          flutter build ipa \
            --release \
            --no-tree-shake-icons \
            --build-name="${BUILD_NAME}" \
            --build-number="${BUILD_NUMBER_VAL}"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY     # محتوى ملف .p8 كـ Base64
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true