workflows:
  ios-appstore:
    name: iOS App Store / TestFlight (auto-sign)
    integrations:
      app_store_connect: CodemagicKey

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote

    scripts:
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get
      - name: Pods
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true