workflows:
  ios-testflight:
    name: iOS TestFlight (auto-sign)
    max_build_duration: 60

    integrations:
      app_store_connect: CodemagicKey   # اسم التكامل عندك (اختياري إذا مفعل من UI)

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drd.ecremote
      groups:
        - app_store_connect              # إذا عم تعتمدي على متغيرات API Key

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Flutter prep
        script: |
          flutter clean
          flutter pub get

      - name: iOS Pods (platform 13.0 + install)
        script: |
          cd ios
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios, '[^']'/platform :ios, '13.0'/" Podfile
          else
            printf "\nplatform :ios, '13.0'\n" >> Podfile
          fi
          pod repo update
          pod install
          cd ..

      - name: Build IPA (auto-sign)
        script: |
          flutter build ipa --release --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        # إذا عم تستخدمي مجموعة المتغيرات
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true