# ios/Podfile
platform :ios, '13.0'
use_frameworks! :linkage => :static
use_modular_headers!

target 'Runner' do
  # Pods for Runner
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['CODE_SIGNING_ALLOWED']  = 'NO'
      c.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      c.build_settings['SKIP_INSTALL']          = 'YES'
    end
  end
  end